# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Coverage precision (number of decimal places)
  precision: 2
  round: down
  range: "70...100"

  status:
    # Overall project coverage
    project:
      default:
        target: auto    # Use coverage of base commit as target
        threshold: 1%   # Allow 1% drop before failing
        if_ci_failed: error

    # Coverage of changed files in PR
    patch:
      default:
        target: 80%     # New code should have 80% coverage
        threshold: 5%   # Allow some flexibility for edge cases
        if_ci_failed: error

# PR comment settings
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true  # Only comment if coverage changed
  require_base: false    # Comment even without base coverage
  require_head: true

# Flags for different test types (expandable later)
flags:
  unittests:
    paths:
      - src/codebook/
    carryforward: true

# Files to ignore in coverage
ignore:
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
  - "setup.py"

# GitHub integration
github_checks:
  annotations: true
